# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ClOrdId', models.BigIntegerField(unique=True)),
                ('OrderId', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('CumQty', models.BigIntegerField()),
                ('OrdStatus', models.CharField(choices=[('0', 'New'), ('1', 'Partially filled'), ('2', 'Filled'), ('4', 'Cancelled'), ('8', 'Rejected'), ('A', 'Pending New')], max_length=1)),
                ('LeavesQty', models.BigIntegerField()),
                ('CxlQty', models.BigIntegerField()),
                ('AvgPx', models.BigIntegerField()),
                ('Symbol', models.CharField(max_length=6)),
                ('Side', models.CharField(choices=[('1', 'BUY'), ('2', 'SELL')], max_length=1)),
                ('OrdType', models.CharField(max_length=1)),
                ('OrderQty', models.BigIntegerField()),
                ('Price', models.BigIntegerField()),
                ('OrderDate', models.DateTimeField()),
                ('Volume', models.BigIntegerField()),
                ('TimeInForce', models.CharField(max_length=1)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
