# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170514_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRL', models.BigIntegerField()),
                ('BRL_locked', models.BigIntegerField()),
                ('BTC', models.BigIntegerField()),
                ('BTC_locked', models.BigIntegerField()),
                ('updated_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ClOrdId',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Side',
            field=models.CharField(choices=[('1', 'BUY'), ('2', 'SELL')], db_index=True, max_length=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='buy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_buy', to='backend.Order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_sell', to='backend.Order'),
        ),
    ]
